# Generated by Django 3.1.3 on 2020-11-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffpersons',
            name='contact',
            field=models.CharField(max_length=10),
        ),
    ]
