# Generated by Django 3.1.3 on 2020-11-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginhandle', '0004_mysale'),
    ]

    operations = [
        migrations.CreateModel(
            name='monthlysale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthname', models.CharField(max_length=40)),
                ('monthprofit', models.IntegerField()),
            ],
        ),
    ]
